name: TranscribeYT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1-beta
    - name: Downloading deepspeech.pbmm
      uses: wei/wget@v1
      with:
        args: -O deepspeech.pbmm https://github.com/mozilla/DeepSpeech/releases/download/v0.9.1/deepspeech-0.9.1-models.pbmm
    - name: Downloading deepspeech.scorer
      uses: wei/wget@v1
      with:
        args: -O deepspeech.scorer https://github.com/mozilla/DeepSpeech/releases/download/v0.9.1/deepspeech-0.9.1-models.scorer
    - name: Getting deepspeech youtube-dl
      run: npm install deepspeech youtube-dl
    - name: sox
      run: sudo apt-get install sox
    - name: Main
      run: node index.js
