name: TranscribeYT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add repo for ffmpeg
      run: sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
    - name: Updating index
      run: sudo apt update
    - name: Getting ffmpeg sox
      run: sudo apt install -y ffmpeg sox
    - name: Downloading deepspeech.pbmm
      uses: wei/wget@v1
      with:
        args: -O deepspeech.pbmm https://github.com/mozilla/DeepSpeech/releases/download/v0.9.1/deepspeech-0.9.1-models.pbmm
    - name: Downloading deepspeech.scorer
      uses: wei/wget@v1
      with:
        args: -O deepspeech.scorer https://github.com/mozilla/DeepSpeech/releases/download/v0.9.1/deepspeech-0.9.1-models.scorer
    - name: Getting deepspeech youtube-dl
      run: npm install deepspeech youtube-dl
    - name: Main
      run: node index.js
